RFC-010 (v1): Document Signing on a Remote Signing Service Provider using Long-Term Certificates
EWC-consortium/eudi-wallet-rfcs pull request #117
Opened 2024-11-29 11:23 UTC by kerk12

This Specification defines the procedures for using the EUDI wallet to digitally sign a document, using Long-Term certificates, on a Remote Signing Service Provider (SSP). It uses the user's PID to identify the user's Certificates. The Signer's Private Keys are stored safely in a Remote Qualified Electronic Signature (RQES) service.

2024-12-02 16:30 UTC, endimion commented
Looks fine guys. My only concern is as follows. This RFC doesn;'t if I understand correctly propose a "registration" phase between the QTSP and the users Wallet. Authentication is implemented over the use of PID only. As PID doesn;t contain any persistent identifier, doesn't this open a window to potential attack vectors? E.g. same name/date of birth to sign a document I am not entitled to sign? 

If you believe this is possible, I would recommend a similar approach to payments, where the EUDI Wallet undergoes a registration phase prior to the signature with the QTSP and then based on the issuance of a "registration credential" the actual signature authoroization is based on this credential presentation.

2024-12-02 16:32 UTC, endimion requested changes
Looks fine guys. My only concern is as follows. This RFC doesn;'t if I understand correctly propose a "registration" phase between the QTSP and the users Wallet. Authentication is implemented over the use of PID only. As PID doesn;t contain any persistent identifier, doesn't this open a window to potential attack vectors? E.g. same name/date of birth to sign a document I am not entitled to sign?

If you believe this is possible, I would recommend a similar approach to payments, where the EUDI Wallet undergoes a registration phase prior to the signature with the QTSP and then based on the issuance of a "registration credential" the actual signature authoroization is based on this credential presentation.

2024-12-03 13:55 UTC, LeoneRiello74 commented on README.md
Hi 
1. credentials/list api requires a bearer token (basic auth  userid/password or oauth2 authorize scope service) to be accessed. do you suppose that the signing provider will collect them after pid verification? so it's transparently managed by the signing provider.... Credentials/list is invoked simply to allow the user to choose the certificate (in case more than two): if only one will be present the user will be forwarded directly to the authorization flow?
2. signature authorization : two options are possible here in the sd, through credentials/authorize and oauth2/authorize in this project we suppose that only the second shoud be considered, no?

2024-12-04 10:59 UTC, kerk12 commented
> Looks fine guys. My only concern is as follows. This RFC doesn;'t if I understand correctly propose a "registration" phase between the QTSP and the users Wallet. Authentication is implemented over the use of PID only. As PID doesn;t contain any persistent identifier, doesn't this open a window to potential attack vectors? E.g. same name/date of birth to sign a document I am not entitled to sign?
> 
> If you believe this is possible, I would recommend a similar approach to payments, where the EUDI Wallet undergoes a registration phase prior to the signature with the QTSP and then based on the issuance of a "registration credential" the actual signature authoroization is based on this credential presentation.

@endimion I have added the QESAC (QES Auth Credential) to authenticate the user, along with a pre-registration phase. Please take a look.

2024-12-04 11:06 UTC, kerk12 commented on README.md
Hi Leone.

1. Service authn/z isn't discussed in the RFC, as noted in the note at the bottom of section 4.3, since different signing services might use different grants (oauth2code, client credentials). Do you reckon I should add the authn/z process as well? 

Also, about the credential selection, it can be done either with a dialog, or, as I just added in the last commit, using the QESAC (see [here](https://github.com/flare-gr/eudi-wallet-rfcs-010-v1/blob/main/ewc-rfc010-long-term-certifice-qes-creation.md#inclusion-of-credential-id-in-the-qesac-optional)).

Now if a user has exactly 1 credentials, the process for the authz of the credential I think should start automatically. I can note that in the RFC too. Thanks for pointing it out.
2. We can do either one, according to CSC spec.  It can be left out to the Signing Service providers to pick the optimal flow for their use case. What do you think?

2024-12-05 07:31 UTC, andreasabr commented on ewc-rfc010-long-term-certifice-qes-creation.md
> +The architecture will be broken down in 4 main phases:
six main phases

2024-12-10 09:17 UTC, kerk12 commented
@LeoneRiello74 @andreasabr @endimion Are the changes ok?

2024-12-11 14:43 UTC, andreasabr approved these changes

2024-12-11 15:28 UTC, kerk12 commented
@lalc I think we are ready to merge.

2024-12-11 20:33 UTC, lalc commented
> @lalc I think we are ready to merge.

Pls go ahead if @andreasabr and @endimion have signed off.

2024-12-12 08:00 UTC, lalc approved these changes

2024-12-12 08:22 UTC, LeoneRiello74 approved these changes

2024-12-12 08:45 UTC, lalc commented
@kerk12 There are merge conflicts that must be fixed in your local branch. I don't have access to your branch now.

2024-12-12 09:56 UTC, kerk12 commented
> @kerk12 There are merge conflicts that must be fixed in your local branch. I don't have access to your branch now.

Done

2024-12-13 17:51 UTC, kerk12 commented
@lalc Can you merge now?

2024-12-13 17:52 UTC, merged