chore: add W3C JWT credential format
EWC-consortium/eudi-wallet-rfcs pull request #54
Opened 2024-05-17 13:57 UTC by mat-work

- Add W3C Verifiable Credential and Presentation format.
- Fix typo

2024-05-17 18:51 UTC, georgepadayatti approved these changes

2024-05-18 11:51 UTC, georgepadayatti requested changes

2024-05-18 11:51 UTC, georgepadayatti commented on ewc-supported-formats.csv
> +W3C JWT - Verifiable Presentation,jwt_vc_json
Shouldn't this be `jwt_vp_json` ?

2024-05-18 11:54 UTC, lalc approved these changes

2024-05-18 21:32 UTC, mat-work commented on ewc-supported-formats.csv
> +W3C JWT - Verifiable Presentation,jwt_vc_json
done

2024-05-18 21:39 UTC, georgepadayatti approved these changes

2024-05-18 21:39 UTC, merged